spring:
  profiles:
    active:
    - dev
---
server:
  port: 8101
spring:
  profiles: dev
  application:
    name: application-provide-8101-config-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/db_01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC # 数据库名称
    username: root
    password: root
mybatis: 
  mapper-locations: com/fykj/providerDept8101/dao/*.xml
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka  
  instance:
    instance-id: spring-boot-provider-dept-8101
    prefer-ip-address: true     #访问路径可以显示IP地址   
      
---
spring:
  profiles: test
  application:
    name: spring-cloud-config-test